### ISSUE TITLE
Error while the plugin try to fetch Munin file(s)

### ISSUE THREAD

**Issue by alex-gulentz** [Invision-Technology-Soultions/ServerMonitor#1]
Hi,

i configured munin plugin and munin is running. Piwik also is allowed to fetch data. After going to Piwik, no reports are shown and the error logs shows:

WARNING ServerMonitor[2015-07-30 20:02:18] [3d5e7] /PATH/piwik/plugins/ServerMonitor/API.php(327): Warning - Wrong parameter count for rrd_fetch() - Piwik 2.14.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING ServerMonitor[2015-07-30 20:02:18] [3d5e7] /PATH/piwik/plugins/ServerMonitor/API.php(328): Warning - array_values() expects parameter 1 to be array, null given - Piwik 2.14.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING ServerMonitor[2015-07-30 20:02:18] [3d5e7] /PATH/piwik/plugins/ServerMonitor/API.php(331): Warning - array_shift() expects parameter 1 to be array, null given - Piwik 2.14.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)
WARNING ServerMonitor[2015-07-30 20:02:18] [3d5e7] /PATH/piwik/plugins/ServerMonitor/API.php(331): Warning - Invalid argument supplied for foreach() - Piwik 2.14.0 - Please report this message in the Piwik forums: http://forum.piwik.org (please do a search first as it might have been reported already)

Lates Verison of Munin is installed, Piwik 2.14

Can you investigate what is the problem?

**Comment by larnold** [comment]
Hi Alex, I have made some changes to support Munin 2.0.25, can you update the plugin and advise if issue is now resolved. Thanks
